# Generated by Django 4.2.1 on 2023-05-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'imagem', 'verbose_name_plural': 'imagens'},
        ),
        migrations.AlterField(
            model_name='image',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/images-products/', verbose_name='imagens do produto'),
        ),
    ]
