# Generated by Django 4.2.1 on 2023-05-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_image_options_alter_image_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/images-products/', verbose_name='imagem de apresentação'),
        ),
    ]
