# Generated by Django 4.2.1 on 2023-05-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_image_cover_alter_product_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images-products/', verbose_name='imagens do produto'),
        ),
    ]
