# Generated by Django 4.2.1 on 2023-05-30 20:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_image_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=15, null=True),
        ),
    ]
